export const enum PartyRelType {
  EMPLOYMENT = 'EMPLOYMENT',

  PURCHASE = 'PURCHASE',

  SALES = 'SALES',

  PARTNERSHIP = 'PARTNERSHIP',

  CONTACT = 'CONTACT',

  CUSTOMER = 'CUSTOMER',

  DISTRCHANNEL = 'DISTRCHANNEL',
}
